Repository looks-to-me/looks-to-me, pull requests merged in 2023-12, with the labels that each got.

#580 [feature] Fix path to db schema
  apps/web/drizzle.config.ts
Labels: feature

#581 [feature] Add a feature to delete posts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/actions/delete-post.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/hooks/use-delete-post.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/index.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/post-menu.stories.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/post-menu.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.css.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/_actions/get-login-user.ts
  apps/web/src/app/_icons/trash-can.svg
  packages/image-cache/src/index.test.ts
  packages/image-cache/src/index.ts
Labels: feature

#591 [feature] Add a feature to Global Confirm Modal
  apps/web/package.json
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/post-menu/hooks/use-delete-post.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-action.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-cancel.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-content.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-description.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-footer.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-provider.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-title.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog-trigger.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog.css.ts
  apps/web/src/app/_components/alert-dialog/alert-dialog.stories.tsx
  apps/web/src/app/_components/alert-dialog/alert-dialog.tsx
  apps/web/src/app/_components/alert-dialog/contexts/alert-dialog-context.ts
  apps/web/src/app/_components/alert-dialog/hooks/use-alert-dialog-disclosure.tsx
  apps/web/src/app/_components/alert-dialog/hooks/use-alert-dialog.ts
  apps/web/src/app/_components/alert-dialog/index.ts
  apps/web/src/app/_components/root/root.tsx
  pnpm-lock.yaml
Labels: feature

#603 [refactor] Delete unused schema types
  apps/web/src/app/_libs/database/schema/tables/images.ts
  apps/web/src/app/_libs/database/schema/tables/post-tags.ts
  apps/web/src/app/_libs/database/schema/tables/posts.ts
  apps/web/src/app/_libs/database/schema/tables/tags.ts
  apps/web/src/app/_libs/database/schema/tables/user-profiles.ts
  apps/web/src/app/_libs/database/schema/tables/user-providers.ts
  apps/web/src/app/_libs/database/schema/tables/users.ts
Labels: refactor

#358 [refactor] Refactor the save function to the database
  apps/web/jest.config.mjs
  apps/web/migrations/0007_real_iron_lad.sql
  apps/web/package.json
  apps/web/src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  apps/web/src/app/(main)/_repositories/image-repository.test.ts
  apps/web/src/app/(main)/_repositories/image-repository.ts
  apps/web/src/app/(main)/_repositories/post-repository.test.ts
  apps/web/src/app/(main)/_repositories/post-repository.ts
  apps/web/src/app/(main)/_repositories/user-provider-repository.test.ts
  apps/web/src/app/(main)/_repositories/user-provider-repository.ts
  apps/web/src/app/(main)/_repositories/user-repository.test.ts
  apps/web/src/app/(main)/_repositories/user-repository.ts
  apps/web/src/app/(main)/auth/callback/route.ts
  apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
  apps/web/src/app/_libs/database/helpers/index.ts
  apps/web/src/app/_libs/database/instance/index.ts
  apps/web/src/app/_libs/database/instance/mock.ts
  apps/web/src/app/_libs/env/index.ts
  apps/web/src/app/_libs/test/setup-database.ts
  apps/web/src/app/_libs/test/setup-worker.ts
  apps/web/tsconfig.json
  apps/web/wrangler.toml
  pnpm-lock.yaml
Labels: refactor

#620 [chore] Delete Interception Route on the post details page.
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/@header/page.css.ts
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/@main/page.css.ts
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/@main/page.tsx
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/layout.css.ts
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/@modal/(.)[atUserName]/posts/[postId]/page.tsx
Labels: chore

#631 refactor: Change the directory of the react hooks
  apps/web/src/app/(main)/@modal/_components/modal-dialog/modal-dialog.tsx
  apps/web/src/components/elements/infinite-scroll/infinite-scroll.tsx
  apps/web/src/hooks/use-in-view-port.ts
  apps/web/src/hooks/use-is-mounted.ts
Labels: refactor

#632 refactor: Change the directory of the helper functions
  apps/web/src/app/(main)/(home)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(profile)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/images/overlays/[word]/route.tsx
  apps/web/src/app/(main)/login/layout.tsx
  apps/web/src/app/(main)/logout/page.tsx
  apps/web/src/app/(main)/new/@auth/page.tsx
  apps/web/src/app/(main)/new/layout.tsx
  apps/web/src/app/(main)/privacy/layout.tsx
  apps/web/src/app/(main)/shuffle/layout.tsx
  apps/web/src/app/(main)/terms/layout.tsx
  apps/web/src/app/_libs/env/index.ts
  apps/web/src/app/layout.tsx
  apps/web/src/components/elements/button/button-icon.tsx
  apps/web/src/components/elements/drop-down-menu/drop-down-menu-icon.tsx
  apps/web/src/components/elements/prefers-color-scheme/prefers-color-scheme.tsx
  apps/web/src/helpers/create-metadata.ts
  apps/web/src/helpers/dispatch.ts
  apps/web/src/helpers/load-google-font.ts
  apps/web/src/helpers/memoize.ts
  apps/web/src/helpers/merge-props.ts
Labels: refactor

#633 refactor: Change the directory of the svg icons
  apps/web/src/app/(main)/_components/application-logo/application-logo.tsx
  apps/web/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  apps/web/src/app/(main)/_components/github-login-button/github-login-button.tsx
  apps/web/src/app/(main)/_components/global-navigation/global-navigation.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/app/(main)/_components/share-button/share-button.tsx
  apps/web/src/components/elements/accessible-icon/accessible-icon.stories.tsx
  apps/web/src/components/elements/button/button.stories.tsx
  apps/web/src/components/elements/dialog/dialog-content.tsx
  apps/web/src/components/elements/sheet/sheet-content.tsx
  apps/web/src/icons/close.svg
  apps/web/src/icons/copy.svg
  apps/web/src/icons/github-black.svg
  apps/web/src/icons/github-white.svg
  apps/web/src/icons/home.svg
  apps/web/src/icons/logout.svg
  apps/web/src/icons/looks-to-me-black.svg
  apps/web/src/icons/looks-to-me-white.svg
  apps/web/src/icons/looks-to-me-with-text-black.svg
  apps/web/src/icons/looks-to-me-with-text-white.svg
  apps/web/src/icons/menu.svg
  apps/web/src/icons/person.svg
  apps/web/src/icons/report.svg
  apps/web/src/icons/shuffle.svg
  apps/web/src/icons/storybook-black.svg
  apps/web/src/icons/storybook-white.svg
  apps/web/src/icons/trash-can.svg
Labels: refactor

#634 refactor: Change the directory of the color themes
  apps/web/src/app/(main)/[atUserName]/(profile)/@header/_components/user-summary/user-summary.css.ts
  apps/web/src/app/(main)/[atUserName]/(profile)/@header/page.css.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.css.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@main/page.css.ts
  apps/web/src/app/(main)/_components/avatar-menu/avatar-menu.css.ts
  apps/web/src/app/(main)/_components/github-login-button/github-login-button.css.ts
  apps/web/src/app/(main)/_components/global-navigation/global-navigation.css.ts
  apps/web/src/app/(main)/_components/login-form/login-form.css.ts
  apps/web/src/app/(main)/_components/page-header/page-header.css.ts
  apps/web/src/app/(main)/_components/post/post.css.ts
  apps/web/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.tsx
  apps/web/src/app/(main)/new/_components/post-create-form/post-create-form.css.ts
  apps/web/src/app/(main)/privacy/page.css.ts
  apps/web/src/app/(main)/terms/page.css.ts
  apps/web/src/components/elements/alert-dialog/alert-dialog.css.ts
  apps/web/src/components/elements/avatar/avatar.css.ts
  apps/web/src/components/elements/breadcrumbs/breadcrumbs.css.ts
  apps/web/src/components/elements/button/button.css.ts
  apps/web/src/components/elements/dialog/dialog.css.ts
  apps/web/src/components/elements/drop-down-menu/drop-down-menu.css.ts
  apps/web/src/components/elements/popover/popover.css.ts
  apps/web/src/components/elements/root/root.css.ts
  apps/web/src/components/elements/separator/separator.css.ts
  apps/web/src/components/elements/sheet/sheet.css.ts
  apps/web/src/components/elements/toaster/toaster.css.ts
  apps/web/src/components/elements/tooltip/tooltip.css.ts
  apps/web/src/themes/dark.css.ts
  apps/web/src/themes/index.ts
  apps/web/src/themes/light.css.ts
  apps/web/src/themes/theme.css.ts
Labels: refactor

#626 [bugfix] Add revalidatePath for post deletion and creation
  apps/web/src/app/(main)/_components/post-menu/actions/delete-post.ts
  apps/web/src/app/(main)/_components/post-menu/post-menu.stories.tsx
  apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
  apps/web/src/app/(main)/new/_components/post-create-form/post-create-form.stories.tsx
Labels: bugfix

#641 refactor: Change the directory of the ApplicationLogo component
  apps/web/src/app/(main)/_components/global-navigation/global-navigation.tsx
  apps/web/src/app/(main)/_components/login-form/login-form.tsx
  apps/web/src/app/(main)/_components/page-header/page-header-presenter.tsx
  apps/web/src/components/domains/application/application-logo/application-logo.css.ts
  apps/web/src/components/domains/application/application-logo/application-logo.stories.tsx
  apps/web/src/components/domains/application/application-logo/application-logo.tsx
  apps/web/src/components/domains/application/application-logo/index.ts
Labels: refactor

#643 refactor: Rename the PageLayout component to ApplicationLayout component
  apps/web/src/app/(main)/(home)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(profile)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/_components/page-layout/index.ts
  apps/web/src/app/(main)/login/layout.tsx
  apps/web/src/app/(main)/new/layout.tsx
  apps/web/src/app/(main)/privacy/layout.tsx
  apps/web/src/app/(main)/shuffle/layout.tsx
  apps/web/src/app/(main)/terms/layout.tsx
  apps/web/src/components/domains/application/application-layout/application-layout.css.ts
  apps/web/src/components/domains/application/application-layout/application-layout.stories.tsx
  apps/web/src/components/domains/application/application-layout/application-layout.tsx
  apps/web/src/components/domains/application/application-layout/index.ts
Labels: refactor

#644 refactor: Rename the GlobalNavigation component to ApplicationNavigat…
  apps/web/src/app/(main)/_components/global-navigation/global-navigation.stories.tsx
  apps/web/src/app/(main)/_components/global-navigation/index.ts
  apps/web/src/app/(main)/_components/page-header/page-header-presenter.tsx
  apps/web/src/components/domains/application/application-navigation/application-navigation.css.ts
  apps/web/src/components/domains/application/application-navigation/application-navigation.stories.tsx
  apps/web/src/components/domains/application/application-navigation/application-navigation.tsx
  apps/web/src/components/domains/application/application-navigation/index.ts
Labels: refactor

#646 refactor: Rename the PageHeader component to ApplicationHeader
  apps/web/src/app/(main)/(home)/@header/page.tsx
  apps/web/src/app/(main)/(home)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@posts/_actions/fetch-user-posts.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@posts/page.css.ts
  apps/web/src/app/(main)/[atUserName]/(details)/@posts/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/_components/user-summary/index.ts
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/_components/user-summary/user-summary.css.ts
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/_components/user-summary/user-summary.stories.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/_components/user-summary/user-summary.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.css.ts
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/layout.css.ts
  apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@main/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.css.ts
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/page.tsx
  apps/web/src/app/(main)/_components/page-header/index.ts
  apps/web/src/app/(main)/_components/page-header/page-header-presenter.tsx
  apps/web/src/app/(main)/_components/page-header/page-header.tsx
  apps/web/src/app/(main)/_components/post-menu/actions/delete-post.ts
  apps/web/src/app/(main)/login/@header/page.tsx
  apps/web/src/app/(main)/login/layout.tsx
  apps/web/src/app/(main)/new/@header/page.tsx
  apps/web/src/app/(main)/new/layout.tsx
  apps/web/src/app/(main)/privacy/@header/page.tsx
  apps/web/src/app/(main)/privacy/layout.tsx
  apps/web/src/app/(main)/shuffle/@header/page.tsx
  apps/web/src/app/(main)/shuffle/layout.tsx
  apps/web/src/app/(main)/terms/@header/page.tsx
  apps/web/src/app/(main)/terms/layout.tsx
  apps/web/src/app/_actions/get-login-user.ts
  apps/web/src/app/_queries/user/get-login-user.ts
  apps/web/src/components/domains/application/application-header/application-header.css.ts
  apps/web/src/components/domains/application/application-header/application-header.stories.tsx
  apps/web/src/components/domains/application/application-header/application-header.tsx
  apps/web/src/components/domains/application/application-header/index.ts
Labels: refactor

#647 refactor: Change the directory of the repositories
  apps/web/src/app/(main)/[atUserName]/(details)/@posts/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/_components/user-summary/user-summary.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@main/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  apps/web/src/app/(main)/_components/post-menu/actions/delete-post.ts
  apps/web/src/app/(main)/_components/post-menu/hooks/use-delete-post.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  apps/web/src/app/(main)/images/avatars/[id]/route.ts
  apps/web/src/app/(main)/images/posts/[id]/raw/route.ts
  apps/web/src/app/(main)/images/posts/[id]/route.ts
  apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
  apps/web/src/app/_queries/user/get-login-user.ts
  apps/web/src/components/domains/application/application-header/application-header.tsx
  apps/web/src/repositories/image-repository.test.ts
  apps/web/src/repositories/image-repository.ts
  apps/web/src/repositories/post-repository.test.ts
  apps/web/src/repositories/post-repository.ts
  apps/web/src/repositories/user-provider-repository.test.ts
  apps/web/src/repositories/user-provider-repository.ts
  apps/web/src/repositories/user-repository.test.ts
  apps/web/src/repositories/user-repository.ts
Labels: refactor

#648 refactor: Change the directory of the UserSummary component
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
  apps/web/src/components/domains/user/user-summary/index.ts
  apps/web/src/components/domains/user/user-summary/user-summary.css.ts
  apps/web/src/components/domains/user/user-summary/user-summary.stories.tsx
  apps/web/src/components/domains/user/user-summary/user-summary.tsx
Labels: refactor

#649 refactor: Make the component not dependent on the repository
  apps/web/src/app/(main)/_components/avatar-menu/index.ts
  apps/web/src/components/domains/application/application-header/application-header.stories.tsx
  apps/web/src/components/domains/application/application-header/application-header.tsx
  apps/web/src/components/domains/user/user-account-menu/index.ts
  apps/web/src/components/domains/user/user-account-menu/user-account-menu.css.ts
  apps/web/src/components/domains/user/user-account-menu/user-account-menu.stories.tsx
  apps/web/src/components/domains/user/user-account-menu/user-account-menu.tsx
  apps/web/src/components/domains/user/user-summary/user-summary.stories.tsx
  apps/web/src/components/domains/user/user-summary/user-summary.tsx
Labels: refactor

#650 refactor: Change the directory of the types
  apps/web/src/app/(main)/(home)/@header/page.tsx
  apps/web/src/app/(main)/(home)/@posts/page.tsx
  apps/web/src/app/(main)/(home)/layout.tsx
  apps/web/src/app/(main)/(home)/page.tsx
  apps/web/src/app/(main)/@modal/(.)login/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@posts/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@main/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/page.tsx
  apps/web/src/app/(main)/layout.tsx
  apps/web/src/app/(main)/login/@header/page.tsx
  apps/web/src/app/(main)/login/layout.tsx
  apps/web/src/app/(main)/login/page.tsx
  apps/web/src/app/(main)/logout/page.tsx
  apps/web/src/app/(main)/new/@auth/page.tsx
  apps/web/src/app/(main)/new/@header/page.tsx
  apps/web/src/app/(main)/new/layout.tsx
  apps/web/src/app/(main)/new/page.tsx
  apps/web/src/app/(main)/privacy/@header/page.tsx
  apps/web/src/app/(main)/privacy/layout.tsx
  apps/web/src/app/(main)/privacy/page.tsx
  apps/web/src/app/(main)/shuffle/@header/page.tsx
  apps/web/src/app/(main)/shuffle/@posts/page.tsx
  apps/web/src/app/(main)/shuffle/layout.tsx
  apps/web/src/app/(main)/shuffle/page.tsx
  apps/web/src/app/(main)/terms/@header/page.tsx
  apps/web/src/app/(main)/terms/layout.tsx
  apps/web/src/app/(main)/terms/page.tsx
  apps/web/src/types/layout-props.ts
  apps/web/src/types/page-props.ts
Labels: refactor

#651 Added overlay text display on input image.
  apps/web/src/app/(main)/images/overlays/[word]/route.tsx
  apps/web/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.css.ts
  apps/web/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.tsx
  apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
  apps/web/src/app/(main)/new/_components/post-create-form/post-create-form.tsx
  apps/web/src/app/(main)/new/_components/variable-text-input/variable-text-input.tsx
  apps/web/src/schemas/post-word-schema.ts
Labels: feature

#652 feature: Make the image preview display debounce
  apps/web/src/app/(main)/new/_components/post-create-form/post-create-form.tsx
Labels: feature

#653 bugfix: Fix a bug that caused an error when creating a migration
  apps/web/migrations/meta/0008_snapshot.json
Labels: bugfix

#654 refactor: Change the directory of the queries
  apps/web/src/app/(main)/(home)/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/(details)/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.tsx
  apps/web/src/app/(main)/_components/post-menu/actions/delete-post.ts
  apps/web/src/app/(main)/login/@header/page.tsx
  apps/web/src/app/(main)/new/@header/page.tsx
  apps/web/src/app/(main)/new/_components/variable-text-input/variable-text-input.tsx
  apps/web/src/app/(main)/privacy/@header/page.tsx
  apps/web/src/app/(main)/shuffle/@header/page.tsx
  apps/web/src/app/(main)/terms/@header/page.tsx
  apps/web/src/app/_queries/user/get-login-user.ts
  apps/web/src/queries/user/get-login-user.test.ts
  apps/web/src/queries/user/get-login-user.ts
Labels: refactor

#661 Add mute user table
  apps/web/migrations/0009_tiresome_shockwave.sql
  apps/web/migrations/meta/0009_snapshot.json
  apps/web/migrations/meta/_journal.json
  apps/web/src/app/_libs/database/helpers/index.ts
  apps/web/src/app/_libs/database/schema/index.ts
  apps/web/src/app/_libs/database/schema/tables/mute-users.ts
  apps/web/src/app/_libs/database/schema/tables/users.ts
Labels: feature

#669 Fix composite primary key order in mute_users table
  apps/web/migrations/0009_tiresome_shockwave.sql
Labels: bugfix

#663 Add Mute User Feature to Post Detail Page
  apps/web/src/app/(main)/[atUserName]/posts/[postId]/@title/page.tsx
  apps/web/src/app/(main)/_components/post-menu/actions/mute-user.test.ts
  apps/web/src/app/(main)/_components/post-menu/actions/mute-user.ts
  apps/web/src/app/(main)/_components/post-menu/actions/unmute-user.test.ts
  apps/web/src/app/(main)/_components/post-menu/actions/unmute-user.ts
  apps/web/src/app/(main)/_components/post-menu/hooks/use-mute-user.tsx
  apps/web/src/app/(main)/_components/post-menu/hooks/use-unmute-user.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/icons/mute.svg
  apps/web/src/icons/unmute.svg
  apps/web/src/repositories/mute-user-repository.test.ts
  apps/web/src/repositories/mute-user-repository.ts
Labels: feature

#670 chore: Adjust the size of the icon
  apps/web/src/app/(main)/_components/github-login-button/github-login-button.css.ts
  apps/web/src/app/(main)/_components/github-login-button/github-login-button.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/components/domains/application/application-navigation/application-navigation.css.ts
  apps/web/src/components/domains/application/application-navigation/application-navigation.tsx
  apps/web/src/components/elements/button/button.css.ts
  apps/web/src/components/elements/drop-down-menu/drop-down-menu.css.ts
  apps/web/src/icons/mute.svg
  apps/web/src/icons/trash-can.svg
  apps/web/src/icons/unmute.svg
Labels: chore

#673 refactor: Change the directory of the mutation actions
  apps/web/src/app/(main)/_components/post-menu/hooks/use-mute-user.tsx
  apps/web/src/app/(main)/_components/post-menu/hooks/use-unmute-user.tsx
  apps/web/src/mutations/user/mute-user.test.ts
  apps/web/src/mutations/user/mute-user.ts
  apps/web/src/mutations/user/unmute-user.test.ts
  apps/web/src/mutations/user/unmute-user.ts
Labels: refactor

#674 Update import paths in user mute/unmute tests
  apps/web/src/mutations/user/mute-user.test.ts
  apps/web/src/mutations/user/unmute-user.test.ts
Labels: bugfix

#677 chore: Make the test run when the pull request is created
  .github/workflows/pr-push-check.yml
  package.json
  turbo.json
Labels: chore

#682 Add timeout 10 minutes to CD pipeline & Fix typo
  .github/workflows/pr-push-check.yml
  .github/workflows/publish.yml
Labels: chore

#688 Refactor submitPost function to use getLoginUser
  apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
Labels: refactor

#678 Add to exclude mute users when retrieving post
  apps/web/src/app/(main)/(home)/@posts/_actions/fetch-posts.test.tsx
  apps/web/src/app/(main)/(home)/@posts/_actions/fetch-posts.tsx
  apps/web/src/app/(main)/shuffle/@posts/_actions/fetch-posts.test.tsx
  apps/web/src/app/(main)/shuffle/@posts/_actions/fetch-posts.tsx
  apps/web/src/app/(main)/shuffle/@posts/page.tsx
  apps/web/src/mutations/user/mute-user.test.ts
  apps/web/src/mutations/user/mute-user.ts
  apps/web/src/mutations/user/unmute-user.test.ts
  apps/web/src/mutations/user/unmute-user.ts
Labels: feature

#691 bugfix: Fix incorrect message displayed after muting a user
  apps/web/src/mutations/user/mute-user.test.ts
  apps/web/src/mutations/user/mute-user.ts
  apps/web/src/mutations/user/unmute-user.test.ts
  apps/web/src/mutations/user/unmute-user.ts
Labels: bugfix

#690 Add settings page
  apps/web/src/app/(main)/settings/(home)/@header/page.tsx
  apps/web/src/app/(main)/settings/(home)/@main/page.css.ts
  apps/web/src/app/(main)/settings/(home)/@main/page.tsx
  apps/web/src/app/(main)/settings/(home)/layout.css.ts
  apps/web/src/app/(main)/settings/(home)/layout.tsx
  apps/web/src/app/(main)/settings/(home)/page.tsx
  apps/web/src/components/domains/user/user-account-menu/user-account-menu.tsx
  apps/web/src/icons/settings.svg
Labels: feature

#693 Add Mute User List Component.
  apps/web/src/app/(main)/settings/(home)/@main/page.css.ts
  apps/web/src/app/(main)/settings/(home)/@main/page.tsx
  apps/web/src/components/domains/user/user-mute-list/index.ts
  apps/web/src/components/domains/user/user-mute-list/user-mute-list-item.css.ts
  apps/web/src/components/domains/user/user-mute-list/user-mute-list-item.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.css.ts
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.stories.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.tsx
Labels: feature

#696 Add logic to mute user list component
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/app/(main)/settings/(home)/@main/page.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list-item.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.stories.tsx
  apps/web/src/hooks/use-unmute-user.tsx
  apps/web/src/queries/user/get-muted-users.test.ts
  apps/web/src/queries/user/get-muted-users.ts
Labels: feature

#700 Add title to Mute user list on settings page
  apps/web/src/app/(main)/settings/(home)/@main/page.css.ts
  apps/web/src/app/(main)/settings/(home)/@main/page.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.css.ts
Labels: feature

#701 refactor: Make minor modifications to the style of the user mute list
  apps/web/src/app/(main)/settings/(home)/@main/page.css.ts
  apps/web/src/app/(main)/settings/(home)/@main/page.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list-item.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.css.ts
  apps/web/src/components/domains/user/user-mute-list/user-mute-list.tsx
Labels: refactor

#702 feature: Change the icon set to lucide
  .scaffdog/component.md
  apps/web/.storybook/main.ts
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/app/(main)/_components/github-login-button/github-login-button.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/app/(main)/_components/share-button/share-button.tsx
  apps/web/src/components/domains/application/application-logo/application-logo.tsx
  apps/web/src/components/domains/application/application-navigation/application-navigation.tsx
  apps/web/src/components/domains/application/application-root/application-root.css.ts
  apps/web/src/components/domains/user/user-account-menu/user-account-menu.tsx
  apps/web/src/components/domains/user/user-mute-list/user-mute-list-item.tsx
  apps/web/src/components/elements/accessible-icon/accessible-icon.stories.tsx
  apps/web/src/components/elements/button/button-icon.tsx
  apps/web/src/components/elements/button/button.css.ts
  apps/web/src/components/elements/button/button.stories.tsx
  apps/web/src/components/elements/dialog/dialog-content.tsx
  apps/web/src/components/elements/drop-down-menu/drop-down-menu-icon.tsx
  apps/web/src/components/elements/drop-down-menu/drop-down-menu.css.ts
  apps/web/src/components/elements/sheet/sheet-content.tsx
  apps/web/src/components/icons/github-icon/github-icon.css.ts
  apps/web/src/components/icons/github-icon/github-icon.stories.tsx
  apps/web/src/components/icons/github-icon/github-icon.tsx
  apps/web/src/components/icons/github-icon/index.ts
  apps/web/src/components/icons/storybook-icon/index.ts
  apps/web/src/components/icons/storybook-icon/storybook-icon.css.ts
  apps/web/src/components/icons/storybook-icon/storybook-icon.stories.tsx
  apps/web/src/components/icons/storybook-icon/storybook-icon.tsx
  apps/web/src/icons/close.svg
  apps/web/src/icons/copy.svg
  apps/web/src/icons/github-black.svg
  apps/web/src/icons/github-white.svg
  apps/web/src/icons/home.svg
  apps/web/src/icons/logout.svg
  apps/web/src/icons/looks-to-me-black.svg
  apps/web/src/icons/looks-to-me-white.svg
  apps/web/src/icons/looks-to-me-with-text-black.svg
  apps/web/src/icons/looks-to-me-with-text-white.svg
  apps/web/src/icons/menu.svg
  apps/web/src/icons/mute.svg
  apps/web/src/icons/person.svg
  apps/web/src/icons/report.svg
  apps/web/src/icons/settings.svg
  apps/web/src/icons/shuffle.svg
  apps/web/src/icons/storybook-black.svg
  apps/web/src/icons/storybook-white.svg
  apps/web/src/icons/trash-can.svg
  apps/web/src/icons/unmute.svg
  apps/web/svgr.d.ts
  apps/web/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#706 feature: Add yellow to the palette
  apps/web/src/themes/dark.css.ts
  apps/web/src/themes/light.css.ts
  apps/web/src/themes/theme.css.ts
Labels: feature

#703 Add mute function to user pages
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.css.ts
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
  apps/web/src/app/(main)/_components/post-menu/post-menu.tsx
  apps/web/src/components/domains/user/user-profile-menu/index.ts
  apps/web/src/components/domains/user/user-profile-menu/user-profile-menu.tsx
  apps/web/src/hooks/use-mute-user.tsx
Labels: feature

#708 Fix so that you can't mute when on your own profile page.
  apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
Labels: bugfix

#707 Add banner component
  apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
  apps/web/src/components/elements/banner/banner.css.ts
  apps/web/src/components/elements/banner/banner.stories.tsx
  apps/web/src/components/elements/banner/banner.tsx
  apps/web/src/components/elements/banner/index.ts
  apps/web/src/themes/dark.css.ts
  apps/web/src/themes/light.css.ts
  apps/web/src/themes/theme.css.ts
Labels: feature

#710 Fixed banner to be displayed only when muted
  apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
  apps/web/src/queries/user/get-is-muted-user-by-name.test.ts
  apps/web/src/queries/user/get-is-muted-user-by-name.ts
Labels: feature
