Repository looks-to-me/looks-to-me, pull requests merged in 2023-09, with the labels that each got.

#224 [feature] User profile page layout
  app/src/app/(main)/[atUserName]/_components/user-summary/index.ts
  app/src/app/(main)/[atUserName]/_components/user-summary/user-summary.css.ts
  app/src/app/(main)/[atUserName]/_components/user-summary/user-summary.stories.tsx
  app/src/app/(main)/[atUserName]/_components/user-summary/user-summary.tsx
  app/src/app/(main)/[atUserName]/_helpers/getUserName.ts
  app/src/app/(main)/[atUserName]/_types/userProfilePageProps.ts
  app/src/app/(main)/[atUserName]/layout.tsx
  app/src/app/(main)/[atUserName]/page.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/page.tsx
  app/src/app/(main)/[atUsername]/page.tsx
Labels: feature

#295 [refactor] Make the profile page the route group
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/index.ts
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.css.ts
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.stories.tsx
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.tsx
  app/src/app/(main)/[atUserName]/(profile)/layout.tsx
  app/src/app/(main)/[atUserName]/(profile)/page.tsx
Labels: refactor

#297 [refactor] Improve page and layout type definitions
  app/src/app/(main)/(home)/@posts/page.tsx
  app/src/app/(main)/(home)/layout.tsx
  app/src/app/(main)/(home)/page.tsx
  app/src/app/(main)/@modal/(.)login/page.tsx
  app/src/app/(main)/[atUserName]/(profile)/layout.tsx
  app/src/app/(main)/[atUserName]/(profile)/page.tsx
  app/src/app/(main)/[atUserName]/_types/userProfilePageProps.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/page.tsx
  app/src/app/(main)/layout.tsx
  app/src/app/(main)/login/layout.tsx
  app/src/app/(main)/login/page.tsx
  app/src/app/(main)/new/@auth/page.tsx
  app/src/app/(main)/new/layout.tsx
  app/src/app/(main)/new/page.tsx
  app/src/app/(main)/privacy/layout.tsx
  app/src/app/(main)/privacy/page.tsx
  app/src/app/(main)/shuffle/@posts/page.tsx
  app/src/app/(main)/shuffle/layout.tsx
  app/src/app/(main)/shuffle/page.tsx
  app/src/app/_types/layout-props.ts
  app/src/app/_types/nextPageProps.ts
  app/src/app/_types/page-props.ts
Labels: refactor

#298 [feature] Add a breadcrumbs component
  app/src/app/(main)/(home)/layout.css.ts
  app/src/app/(main)/(home)/layout.tsx
  app/src/app/(main)/[atUserName]/(profile)/layout.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  app/src/app/(main)/login/layout.css.ts
  app/src/app/(main)/login/layout.tsx
  app/src/app/(main)/new/layout.css.ts
  app/src/app/(main)/new/layout.tsx
  app/src/app/(main)/privacy/layout.css.ts
  app/src/app/(main)/privacy/layout.tsx
  app/src/app/(main)/shuffle/layout.css.ts
  app/src/app/(main)/shuffle/layout.tsx
  app/src/app/_components/breadcrumbs/breadcrumbs-item.tsx
  app/src/app/_components/breadcrumbs/breadcrumbs.css.ts
  app/src/app/_components/breadcrumbs/breadcrumbs.stories.tsx
  app/src/app/_components/breadcrumbs/breadcrumbs.tsx
  app/src/app/_components/breadcrumbs/index.ts
Labels: feature

#299 [feature] Add a drop down menu component
  app/package.json
  app/src/app/(main)/_components/avatar-menu/avatar-menu.css.ts
  app/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  app/src/app/(main)/_components/logout-button/index.ts
  app/src/app/(main)/_components/logout-button/logout-button.stories.tsx
  app/src/app/(main)/_components/logout-button/logout-button.tsx
  app/src/app/(main)/logout/page.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-content.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-group.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-icon.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-item.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-label.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu-trigger.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu.css.ts
  app/src/app/_components/drop-down-menu/drop-down-menu.stories.tsx
  app/src/app/_components/drop-down-menu/drop-down-menu.tsx
  app/src/app/_components/drop-down-menu/index.ts
  app/src/app/_components/separator/separator.tsx
  app/src/app/_icons/logout.svg
  app/src/app/_icons/person.svg
  app/src/app/_theme/dark.css.ts
  app/src/app/_theme/light.css.ts
  pnpm-lock.yaml
Labels: feature

#301 [feature] Add a image display on the post detail page
  app/src/app/(main)/[atUserName]/posts/[postId]/@header/page.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/@main/page.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/@main/page.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
Labels: feature

#302 [feature] Add a link to the post details page
  app/src/app/(main)/(home)/@posts/_actions/fetch-posts.tsx
  app/src/app/(main)/_components/post-list/post-list.stories.tsx
  app/src/app/(main)/_components/post/post.css.ts
  app/src/app/(main)/_components/post/post.stories.tsx
  app/src/app/(main)/_components/post/post.tsx
  app/src/app/(main)/shuffle/@posts/_actions/fetch-posts.tsx
Labels: feature

#305 [bugfix] Fix error querying DB on shuffle page
  app/src/app/(main)/shuffle/@posts/_actions/fetch-posts.tsx
Labels: bugfix

#306 [feature] Add a dialog component for intercept routes
  app/src/app/(main)/@modal/(.)login/_components/login-dialog/index.ts
  app/src/app/(main)/@modal/(.)login/_components/login-dialog/login-dialog.stories.tsx
  app/src/app/(main)/@modal/(.)login/_components/login-dialog/login-dialog.tsx
  app/src/app/(main)/@modal/(.)login/layout.tsx
  app/src/app/(main)/@modal/(.)login/page.css.ts
  app/src/app/(main)/@modal/(.)login/page.tsx
  app/src/app/(main)/@modal/_components/modal-dialog/index.ts
  app/src/app/(main)/@modal/_components/modal-dialog/modal-dialog.css.ts
  app/src/app/(main)/@modal/_components/modal-dialog/modal-dialog.stories.tsx
  app/src/app/(main)/@modal/_components/modal-dialog/modal-dialog.tsx
  app/src/app/(main)/login/page.tsx
Labels: feature

#303 [feature] feature/user profile page details
  app/src/app/(main)/[atUserName]/(profile)/@header/page.css.ts
  app/src/app/(main)/[atUserName]/(profile)/@header/page.tsx
  app/src/app/(main)/[atUserName]/(profile)/@posts/_actions/fetch-user-posts.tsx
  app/src/app/(main)/[atUserName]/(profile)/@posts/page.css.ts
  app/src/app/(main)/[atUserName]/(profile)/@posts/page.tsx
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.tsx
  app/src/app/(main)/[atUserName]/(profile)/layout.css.ts
  app/src/app/(main)/[atUserName]/(profile)/layout.tsx
  app/src/app/(main)/[atUserName]/(profile)/page.tsx
  app/src/app/(main)/_repositories/post-repository.ts
Labels: feature

#307 [feature] Add a share button
  .github/workflows/publish.yml
  app/.env
  app/src/app/(main)/[atUserName]/posts/[postId]/@header/_components/share-button/share-button.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
  app/src/app/(main)/_components/share-button/index.ts
  app/src/app/(main)/_components/share-button/share-button.stories.tsx
  app/src/app/(main)/_components/share-button/share-button.tsx
  app/src/app/_libs/env/index.ts
Labels: feature

#308 [feature] Add a upper limit to the height of the image
  app/src/app/(main)/@modal/(.)login/layout.tsx
  app/src/app/(main)/@modal/_components/modal-dialog/modal-dialog.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/@main/page.css.ts
  app/src/app/(main)/[atUserName]/posts/[postId]/@main/page.tsx
  app/src/app/(main)/_components/post/post.css.ts
  app/src/app/_components/dialog/dialog-content.tsx
  app/src/app/_components/dialog/dialog.stories.tsx
Labels: feature

#309 [feature] Make the generated images cache in R2 storage
  app/src/app/(main)/images/_helpers/image-cache.ts
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/route.ts
Labels: feature

#310 [feature] Make use of lighter formats when compositing images
  app/src/app/(main)/images/posts/[id]/route.ts
  workers/image-overlay/src/worker.ts
Labels: feature

#311 [feature] Enable CloudflareImages automatic format determination
  app/next.loader.js
Labels: feature

#312 [chore] Make the worker public using the wrangler cli
  .github/workflows/publish.yml
Labels: chore

#313 [feature] Make it respect the format of the original image if the acc…
  app/src/app/(main)/images/posts/[id]/route.ts
  workers/image-overlay/src/worker.ts
Labels: feature

#315 [bugfix] Remove the breadcrumb list because it contained unnecessary …
  app/src/app/_components/breadcrumbs/breadcrumbs.css.ts
Labels: bugfix

#317 [bugfix] Use 'and' operator to combine filters
  app/src/app/(main)/[atUserName]/(profile)/@posts/_actions/fetch-user-posts.tsx
Labels: bugfix

#318 [bugfix] Fix a bug that was preventing icons from being displayed on …
  app/src/app/(main)/[atUserName]/(profile)/@header/_components/user-summary/index.ts
  app/src/app/(main)/[atUserName]/(profile)/@header/_components/user-summary/user-summary.css.ts
  app/src/app/(main)/[atUserName]/(profile)/@header/_components/user-summary/user-summary.stories.tsx
  app/src/app/(main)/[atUserName]/(profile)/@header/_components/user-summary/user-summary.tsx
  app/src/app/(main)/[atUserName]/(profile)/@header/page.tsx
  app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.tsx
  app/src/app/(main)/_components/avatar-menu/avatar-menu.css.ts
  app/src/app/(main)/_repositories/post-repository.ts
Labels: bugfix

#316 [feature] logo and ogp
  app/public/looks-to-me-with-text-black.png
  app/public/looks-to-me-with-text-white.png
  app/src/app/(main)/(home)/layout.tsx
  app/src/app/(main)/[atUserName]/(profile)/layout.tsx
  app/src/app/(main)/[atUserName]/posts/[postId]/layout.tsx
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.css.ts
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.stories.tsx
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.tsx
  app/src/app/(main)/_components/application-logo-with-text/index.ts
  app/src/app/(main)/_components/github-login-button/github-login-button.css.ts
  app/src/app/(main)/_components/login-form/login-form.css.ts
  app/src/app/(main)/_components/login-form/login-form.tsx
  app/src/app/(main)/login/layout.tsx
  app/src/app/(main)/new/layout.tsx
  app/src/app/(main)/privacy/layout.tsx
  app/src/app/(main)/shuffle/layout.tsx
  app/src/app/(main)/terms/layout.tsx
  app/src/app/_helpers/create-metadata.ts
  app/src/app/_icons/looks-to-me-with-text-black.svg
  app/src/app/_icons/looks-to-me-with-text-white.svg
  app/src/app/layout.tsx
Labels: feature

#319 [bugfix] Fix a bug that the color of the application logo is not refl…
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.css.ts
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.stories.tsx
  app/src/app/(main)/_components/application-logo-with-text/application-logo-with-text.tsx
  app/src/app/(main)/_components/application-logo-with-text/index.ts
  app/src/app/(main)/_components/application-logo/application-logo.css.ts
  app/src/app/(main)/_components/application-logo/application-logo.stories.tsx
  app/src/app/(main)/_components/application-logo/application-logo.tsx
  app/src/app/(main)/_components/global-navigation/global-navigation.css.ts
  app/src/app/(main)/_components/login-form/login-form.tsx
  app/src/app/(main)/_components/page-header/page-header.css.ts
  app/src/app/_icons/looks-to-me-black.svg
  app/src/app/_icons/looks-to-me-white.svg
  app/src/app/_icons/looks-to-me-with-text-black.svg
  app/src/app/_icons/looks-to-me-with-text-white.svg
Labels: bugfix

#320 [feature] Change OG image color code from '#000' to '#1f2328'
  app/public/looks-to-me-with-text-black.png
  app/public/looks-to-me-with-text-white.png
Labels: feature

#321 [bugfix] Set width to svg logo
  app/src/app/(main)/_components/application-logo/application-logo.tsx
Labels: bugfix

#322 [feature] Make it so that the user is redirected to the submission de…
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
  app/src/app/(main)/new/_components/post-create-form/post-create-form.tsx
Labels: feature

#323 [refactor] Remove unnecessary props
  app/src/app/(main)/_components/application-logo/application-logo.tsx
Labels: refactor

#324 [feature] Make only successful responses be cached
  app/src/app/(main)/images/_helpers/image-cache.ts
Labels: feature

#325 [feature] Make the posted images pre-cached after the posted is complete
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
Labels: feature

#326 [bugfix] Fix a bug that caused the pre-cache to be canceled
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
Labels: bugfix

#329 [feature] Make the data be deleted if the image conversion fails
  app/src/app/(main)/_repositories/image-repository.ts
  app/src/app/(main)/_repositories/post-repository.ts
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/route.ts
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
  workers/image-overlay/src/worker.ts
Labels: feature

#332 [feature] Add a worker to cache CloudflareImages responses
  .github/workflows/consistent-pull-request.yml
  .github/workflows/publish.yml
  .npmrc
  app/.env
  app/next.config.js
  app/next.loader.js
  app/next.loader.ts
  app/package.json
  app/src/app/(main)/images/_helpers/image-cache.ts
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/route.ts
  app/src/app/_libs/env/index.ts
  packages/image-cache/.eslintrc.json
  packages/image-cache/package.json
  packages/image-cache/src/index.ts
  packages/image-cache/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  workers/cdn/.eslintrc.json
  workers/cdn/package.json
  workers/cdn/src/worker.ts
  workers/cdn/tsconfig.json
  workers/cdn/worker-configuration.d.ts
  workers/cdn/wrangler.toml
Labels: feature

#333 [chore] Make it possible to create pull requests in the preview branch
  .github/workflows/consistent-pull-request.yml
Labels: chore

#337 [chore] Make it possible to create pull requests in the preview branch
  .github/workflows/consistent-pull-request.yml
Labels: chore

#340 [bugfix] Fix incorrect cache control config for raw images
  app/src/app/(main)/images/posts/[id]/raw/route.ts
Labels: bugfix

#341 [bugfix] Fix a cache control config that was missing in some areas
  app/src/app/(main)/images/posts/[id]/route.ts
  packages/image-cache/src/index.ts
Labels: bugfix

#342 [bugfix] Fix incorrect string for copying links to posted images
  app/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
Labels: bugfix

#345 [bugfix] Revert back to cache control due to errors in Cloudflare Images
  app/src/app/(main)/images/posts/[id]/raw/route.ts
Labels: bugfix

#353 [refactor] Make the post detail page do not prefetch
  app/src/app/(main)/_components/post/post.tsx
Labels: refactor

#355 [refactor] Fix missing foreign key settings in user-related tables
  app/migrations/0007_real_iron_lad.sql
  app/migrations/meta/0007_snapshot.json
  app/migrations/meta/_journal.json
  app/src/app/_libs/db/schema/tables/user-profiles.ts
  app/src/app/_libs/db/schema/tables/user-providers.ts
Labels: refactor

#357 [feature] Add tags and post_tags tables
  app/migrations/0008_giant_pete_wisdom.sql
  app/migrations/meta/0008_snapshot.json
  app/migrations/meta/_journal.json
  app/src/app/_libs/db/schema/index.ts
  app/src/app/_libs/db/schema/tables/post-tags.ts
  app/src/app/_libs/db/schema/tables/posts.ts
  app/src/app/_libs/db/schema/tables/tags.ts
Labels: feature
