Repository looks-to-me/looks-to-me, pull requests merged in 2023-08, with the labels that each got.

#147 [feature] Make it use SQLiteWASM when working with Storybook
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.tsx
  next.config.js
  package.json
  pnpm-lock.yaml
  public/.gitkeep
  sqlite-wasm.d.ts
  src/app/_components/global-navigation/global-navigation.tsx
  src/app/_libs/db/index.ts
  src/app/_libs/db/instance/index.ts
  src/app/_libs/db/instance/mock.ts
  tsconfig.json
Labels: feature

#154 [feature] Add a toaster component
  package.json
  pnpm-lock.yaml
  src/app/_components/root/root.tsx
  src/app/_components/toaster/index.ts
  src/app/_components/toaster/toaster.css.ts
  src/app/_components/toaster/toaster.stories.tsx
  src/app/_components/toaster/toaster.tsx
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#157 [bugfix] Fix incorrect color of toast shadow
  src/app/_components/toaster/toaster.css.ts
Labels: bugfix

#158 [feature] Add a popover component
  package.json
  pnpm-lock.yaml
  src/app/_components/popover/index.ts
  src/app/_components/popover/popover-content.tsx
  src/app/_components/popover/popover-trigger.tsx
  src/app/_components/popover/popover.css.ts
  src/app/_components/popover/popover.stories.tsx
  src/app/_components/popover/popover.tsx
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#160 [deps] Update dependency cf-bindings-proxy to v0.2.6
  package.json
  patches/cf-bindings-proxy@0.2.5.patch
  pnpm-lock.yaml
Labels: deps

#162 [feature] Add a dialog component
  src/app/_components/dialog/dialog-close.tsx
  src/app/_components/dialog/dialog-content.tsx
  src/app/_components/dialog/dialog-description.tsx
  src/app/_components/dialog/dialog-title.tsx
  src/app/_components/dialog/dialog-trigger.tsx
  src/app/_components/dialog/dialog.css.ts
  src/app/_components/dialog/dialog.stories.tsx
  src/app/_components/dialog/dialog.tsx
  src/app/_components/dialog/index.ts
Labels: feature

#163 [refactor] Add a main route group
  src/app/(main)/_components/global-navigation/global-navigation.css.ts
  src/app/(main)/_components/global-navigation/global-navigation.stories.tsx
  src/app/(main)/_components/global-navigation/global-navigation.tsx
  src/app/(main)/_components/global-navigation/index.ts
  src/app/(main)/_components/header/header.css.ts
  src/app/(main)/_components/header/header.stories.tsx
  src/app/(main)/_components/header/header.tsx
  src/app/(main)/_components/header/index.ts
  src/app/(main)/_components/login-button/index.ts
  src/app/(main)/_components/login-button/login-button.css.ts
  src/app/(main)/_components/login-button/login-button.stories.tsx
  src/app/(main)/_components/login-button/login-button.tsx
  src/app/(main)/_components/logo/index.ts
  src/app/(main)/_components/logo/logo.css.ts
  src/app/(main)/_components/logo/logo.stories.tsx
  src/app/(main)/_components/logo/logo.tsx
  src/app/(main)/_components/logout-button/index.ts
  src/app/(main)/_components/logout-button/logout-button.stories.tsx
  src/app/(main)/_components/logout-button/logout-button.tsx
  src/app/(main)/auth/callback/route.ts
  src/app/(main)/page.tsx
Labels: refactor

#165 [feature] Add a infinite scroll component
  src/app/_components/infinite-scroll/index.ts
  src/app/_components/infinite-scroll/infinite-scroll.css.ts
  src/app/_components/infinite-scroll/infinite-scroll.stories.tsx
  src/app/_components/infinite-scroll/infinite-scroll.tsx
  src/app/_hooks/useInViewPort.ts
Labels: feature

#91 [feature] Add Image Upload Page
  migrations/0001_goofy_titania.sql
  migrations/meta/0001_snapshot.json
  migrations/meta/_journal.json
  package.json
  pnpm-lock.yaml
  src/app/(main)/posts/new/_components/input-image-with-preview/index.ts
  src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.css.ts
  src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.stories.tsx
  src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
  src/app/(main)/posts/new/_components/post-create-form/index.ts
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.css.ts
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.stories.tsx
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
  src/app/(main)/posts/new/page.tsx
  src/app/_libs/db/schema/index.ts
  src/app/_libs/db/schema/tables/images.ts
  src/app/_libs/db/schema/tables/users.ts
  src/app/_libs/storage/index.ts
Labels: feature

#177 [feature] Add a custom image loader
  next.config.js
  next.loader.js
  src/app/(main)/images/overlays/[word]/route.tsx
  src/app/(main)/images/posts/[id]/route.ts
Labels: feature

#181 [bugfix] Fix the string normalization process for overlay images
  src/app/(main)/images/overlays/[word]/route.tsx
Labels: bugfix

#188 [refactor] Make the satisfies operator be used instead of the type an…
  .scaffdog/component.md
  src/app/(main)/_components/global-navigation/global-navigation.stories.tsx
  src/app/(main)/_components/header/header.stories.tsx
  src/app/(main)/_components/login-button/login-button.stories.tsx
  src/app/(main)/_components/logo/logo.stories.tsx
  src/app/(main)/_components/logout-button/logout-button.stories.tsx
  src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.stories.tsx
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.stories.tsx
  src/app/_components/accessible-icon/accessible-icon.stories.tsx
  src/app/_components/button/button.stories.tsx
  src/app/_components/dialog/dialog.stories.tsx
  src/app/_components/infinite-scroll/infinite-scroll.stories.tsx
  src/app/_components/popover/popover.stories.tsx
  src/app/_components/prefers-color-scheme/prefers-color-scheme.stories.tsx
  src/app/_components/separator/separator.stories.tsx
  src/app/_components/sheet/sheet.stories.tsx
  src/app/_components/toaster/toaster.stories.tsx
  src/app/_components/tooltip/tooltip.stories.tsx
  src/app/_components/visually-hidden/visually-hidden.stories.tsx
Labels: refactor

#189 [feature] Add a aspect ratio component
  package.json
  pnpm-lock.yaml
  src/app/_components/aspect-ratio/aspect-ratio.stories.tsx
  src/app/_components/aspect-ratio/aspect-ratio.tsx
  src/app/_components/aspect-ratio/index.ts
Labels: feature

#186 [feature] userテーブルにカラムいくつか追加
  migrations/0000_nasty_mongoose.sql
  migrations/0000_unique_lilith.sql
  migrations/0001_goofy_titania.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/0001_snapshot.json
  migrations/meta/_journal.json
  src/app/_libs/db/schema/tables/users.ts
Labels: feature

#194 [feature] Add a posts table
  migrations/0001_melodic_stardust.sql
  migrations/0002_violet_malcolm_colcord.sql
  migrations/meta/0001_snapshot.json
  migrations/meta/0002_snapshot.json
  migrations/meta/_journal.json
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
  src/app/_libs/db/schema/index.ts
  src/app/_libs/db/schema/tables/images.ts
  src/app/_libs/db/schema/tables/posts.ts
  src/app/_libs/db/schema/tables/users.ts
Labels: feature

#204 [refactor] Make it so that the authenticated user is retrieved inside…
  src/app/(main)/_components/header/header-presenter.tsx
  src/app/(main)/_components/header/header.stories.tsx
  src/app/(main)/_components/header/header.tsx
  src/app/(main)/page.tsx
Labels: refactor

#209 [deps] Update dependency wrangler to v3.4.0
  package.json
  pnpm-lock.yaml
Labels: deps

#190 [feature] ログイン時にDBにユーザー情報をupsert
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  src/app/(main)/_components/sync-o-auth-user/index.ts
  src/app/(main)/_components/sync-o-auth-user/sync-o-auth-user.tsx
  src/app/_components/root/root.tsx
Labels: feature

#212 [feature] Add a post list
  src/app/(main)/(home)/@posts/_components/post-list/actions/fetch-posts.tsx
  src/app/(main)/(home)/@posts/_components/post-list/index.ts
  src/app/(main)/(home)/@posts/_components/post-list/post-list-presenter.tsx
  src/app/(main)/(home)/@posts/_components/post-list/post-list.css.ts
  src/app/(main)/(home)/@posts/_components/post-list/post-list.stories.tsx
  src/app/(main)/(home)/@posts/_components/post-list/post-list.tsx
  src/app/(main)/(home)/@posts/_components/post/index.ts
  src/app/(main)/(home)/@posts/_components/post/post.css.ts
  src/app/(main)/(home)/@posts/_components/post/post.stories.tsx
  src/app/(main)/(home)/@posts/_components/post/post.tsx
  src/app/(main)/(home)/@posts/page.tsx
  src/app/(main)/(home)/layout.css.ts
  src/app/(main)/(home)/layout.tsx
  src/app/(main)/(home)/page.tsx
  src/app/(main)/page.tsx
  src/app/_components/infinite-scroll/infinite-scroll.stories.tsx
  src/app/_components/infinite-scroll/infinite-scroll.tsx
Labels: feature

#87 [feature] Add user profile page
  next.config.js
  src/app/[atUsername]/page.tsx
  src/app/_types/nextPageProps.ts
Labels: feature

#218 [refactor] Move user page to (main) directory
  src/app/(main)/[atUsername]/page.tsx
Labels: refactor

#221 [feature] Add a button icon component
  src/app/(main)/_components/global-navigation/global-navigation.tsx
  src/app/_components/button/button-icon.tsx
  src/app/_components/button/button.css.ts
  src/app/_components/button/button.stories.tsx
  src/app/_components/button/index.ts
  src/app/_components/dialog/dialog-content.tsx
  src/app/_components/sheet/sheet-content.tsx
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#222 [feature] displayNameをnullableにした
  migrations/0003_tired_onslaught.sql
  migrations/meta/0003_snapshot.json
  migrations/meta/_journal.json
  src/app/(main)/_components/sync-o-auth-user/sync-o-auth-user.tsx
  src/app/_libs/auth/server/get-auth-user.ts
  src/app/_libs/auth/type/auth-user.ts
  src/app/_libs/db/schema/tables/users.ts
Labels: feature

#213 [feature] fix size and color of overlay iamge
  src/app/(main)/images/overlays/[word]/route.tsx
Labels: feature

#233 [bugfix] Fix forgot to write migration of users table
  migrations/0003_tired_onslaught.sql
Labels: bugfix

#234 [refactor] Move post list component to (main) directory
  src/app/(main)/(home)/@posts/_actions/fetch-posts.tsx
  src/app/(main)/(home)/@posts/_components/post-list/post-list.tsx
  src/app/(main)/(home)/@posts/page.tsx
  src/app/(main)/_components/post-list/index.ts
  src/app/(main)/_components/post-list/post-list.css.ts
  src/app/(main)/_components/post-list/post-list.stories.tsx
  src/app/(main)/_components/post-list/post-list.tsx
  src/app/(main)/_components/post/index.ts
  src/app/(main)/_components/post/post.css.ts
  src/app/(main)/_components/post/post.stories.tsx
  src/app/(main)/_components/post/post.tsx
Labels: refactor

#238 [feature] Make the page title a link
  src/app/(main)/(home)/page.css.ts
  src/app/(main)/(home)/page.tsx
  src/app/(main)/shuffle/page.css.ts
  src/app/(main)/shuffle/page.tsx
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
Labels: feature

#244 [chore] Disable trailing slash option
  next.config.js
Labels: chore

#220 [feature] ログインボタンをgithubっぽいスタイルにした
  src/app/(main)/_components/github-login-button/github-login-button.css.ts
  src/app/(main)/_components/github-login-button/github-login-button.stories.tsx
  src/app/(main)/_components/github-login-button/github-login-button.tsx
  src/app/(main)/_components/github-login-button/index.ts
  src/app/(main)/_components/header/header-presenter.tsx
  src/app/(main)/_components/login-button/index.ts
  src/app/(main)/_components/login-button/login-button.css.ts
Labels: feature

#252 [feature] Add a favicon
  next.config.js
  public/.gitkeep
  public/favicon.ico
  src/app/apple-icon.png
  src/app/icon.svg
Labels: feature

#256 [feature] [fix] Corrected setup procedure in README
  README.md
Labels: feature

#217 [feature] 画像を実際にアップロードする処理を追加
  src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
  src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
  src/app/_libs/env/index.ts
  src/app/_libs/storage/index.ts
  wrangler.toml
Labels: feature

#259 [chore] Add a image overlay worker project
  pnpm-lock.yaml
  workers/image-overlay/.eslintrc.json
  workers/image-overlay/package.json
  workers/image-overlay/src/index.ts
  workers/image-overlay/tsconfig.json
  workers/image-overlay/worker-configuration.d.ts
  workers/image-overlay/wrangler.toml
Labels: chore

#258 [feature]アカウント周りのUI追加
  app/next.config.js
  app/src/app/(main)/_components/avatar-and-user-menu/avatar-and-user-menu.css.ts
  app/src/app/(main)/_components/avatar-and-user-menu/avatar-and-user-menu.stories.tsx
  app/src/app/(main)/_components/avatar-and-user-menu/avatar-and-user-menu.tsx
  app/src/app/(main)/_components/avatar-and-user-menu/index.ts
  app/src/app/(main)/_components/header/header-presenter.tsx
  app/src/app/(main)/_components/login-button-and-dialog/index.ts
  app/src/app/(main)/_components/login-button-and-dialog/login-button-and-dialog.css.ts
  app/src/app/(main)/_components/login-button-and-dialog/login-button-and-dialog.stories.tsx
  app/src/app/(main)/_components/login-button-and-dialog/login-button-and-dialog.tsx
Labels: feature

#260 [feature] add image-overlay workers
  .github/workflows/publish.yml
  pnpm-lock.yaml
  workers/image-overlay/package.json
  workers/image-overlay/src/image-size/README.md
  workers/image-overlay/src/image-size/gif.ts
  workers/image-overlay/src/image-size/jpeg.ts
  workers/image-overlay/src/image-size/png.ts
  workers/image-overlay/src/image-size/utils.ts
  workers/image-overlay/src/index.ts
  workers/image-overlay/src/worker.ts
  workers/image-overlay/tsconfig.json
  workers/image-overlay/wrangler.toml
Labels: feature

#261 [feature] Add a privacy policy page
  app/src/app/(main)/_components/global-navigation/global-navigation.css.ts
  app/src/app/(main)/_components/global-navigation/global-navigation.tsx
  app/src/app/(main)/_components/header/header-presenter.tsx
  app/src/app/(main)/_components/login-button-and-dialog/index.ts
  app/src/app/(main)/_components/login-button-and-dialog/login-button-and-dialog.stories.tsx
  app/src/app/(main)/_components/login-button/index.ts
  app/src/app/(main)/_components/login-button/login-button.css.ts
  app/src/app/(main)/_components/login-button/login-button.stories.tsx
  app/src/app/(main)/_components/login-button/login-button.tsx
  app/src/app/(main)/privacy/page.css.ts
  app/src/app/(main)/privacy/page.tsx
Labels: feature

#263 [deps] Update dependency cf-bindings-proxyto v0.3.1
  app/package.json
  pnpm-lock.yaml
Labels: deps

#264 [feature] Add a privacy policy page title
  app/src/app/(main)/privacy/page.tsx
Labels: feature

#266 [bugfix] Avoid using transaction
  app/src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  app/src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
Labels: bugfix

#262 [feature] 投稿画面を整えた
  app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.css.ts
  app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
  app/src/app/(main)/posts/new/_components/post-create-form/post-create-form.css.ts
  app/src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
  app/src/app/(main)/posts/new/_components/variable-text-input/index.ts
  app/src/app/(main)/posts/new/_components/variable-text-input/variable-text-input.css.ts
  app/src/app/(main)/posts/new/_components/variable-text-input/variable-text-input.stories.tsx
  app/src/app/(main)/posts/new/_components/variable-text-input/variable-text-input.tsx
  app/src/app/(main)/posts/new/page.tsx
Labels: feature

#267 [feature] Make it possible to retrieve posted images
  app/.env
  app/src/app/(main)/(home)/@posts/_actions/fetch-posts.tsx
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/README.md
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/index.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/gif.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/jpeg.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/png.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/utils.ts
  app/src/app/(main)/images/posts/[id]/raw/route.ts
  app/src/app/(main)/images/posts/[id]/route.ts
  app/src/app/(main)/posts/new/_components/post-create-form/actions/submitPost.ts
  app/src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
  app/src/app/(main)/shuffle/@posts/_actions/fetch-posts.tsx
  app/src/app/_libs/env/index.ts
  app/src/app/_libs/storage/index.ts
  pnpm-lock.yaml
  workers/image-overlay/.dev.vars
  workers/image-overlay/package.json
  workers/image-overlay/src/worker.ts
  workers/image-overlay/worker-configuration.d.ts
  workers/image-overlay/wrangler.toml
Labels: feature

#268 [deps] Update dependency @cloudflare/next-on-pages to v1.6.0
  app/package.json
  pnpm-lock.yaml
Labels: deps

#270 [bugfix] fix overflow when selecting large images.
  app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.css.ts
  app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
Labels: bugfix

#279 [feature] Add a new post button
  app/src/app/(main)/@modal/(.)login/_components/login-dialog/login-dialog.stories.tsx
  app/src/app/(main)/_components/header/header-presenter.tsx
  app/src/app/(main)/_components/link-button/index.ts
  app/src/app/(main)/_components/link-button/link-button.stories.tsx
  app/src/app/(main)/_components/link-button/link-button.tsx
  app/src/app/(main)/_components/login-button/login-button.css.ts
  app/src/app/(main)/_components/login-button/login-button.tsx
  app/src/app/(main)/_components/login-form/login-form.css.ts
  app/src/app/(main)/_components/login-form/login-form.stories.tsx
  app/src/app/(main)/_components/new-post-button/index.ts
  app/src/app/(main)/_components/new-post-button/new-post-button.stories.tsx
  app/src/app/(main)/_components/new-post-button/new-post-button.tsx
  app/src/app/(main)/new/@auth/page.tsx
  app/src/app/(main)/new/_components/input-image-with-preview/index.ts
  app/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.css.ts
  app/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.stories.tsx
  app/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.tsx
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
  app/src/app/(main)/new/_components/post-create-form/index.ts
  app/src/app/(main)/new/_components/post-create-form/post-create-form.css.ts
  app/src/app/(main)/new/_components/post-create-form/post-create-form.stories.tsx
  app/src/app/(main)/new/_components/post-create-form/post-create-form.tsx
  app/src/app/(main)/new/_components/variable-text-input/index.ts
  app/src/app/(main)/new/_components/variable-text-input/variable-text-input.css.ts
  app/src/app/(main)/new/_components/variable-text-input/variable-text-input.stories.tsx
  app/src/app/(main)/new/_components/variable-text-input/variable-text-input.tsx
  app/src/app/(main)/new/layout.css.ts
  app/src/app/(main)/new/layout.tsx
  app/src/app/(main)/new/page.tsx
Labels: feature

#280 [feature] Replace the logo
  app/src/app/(main)/(home)/layout.tsx
  app/src/app/(main)/_components/application-logo/application-logo.css.ts
  app/src/app/(main)/_components/application-logo/application-logo.stories.tsx
  app/src/app/(main)/_components/application-logo/application-logo.tsx
  app/src/app/(main)/_components/application-logo/index.ts
  app/src/app/(main)/_components/global-navigation/global-navigation.css.ts
  app/src/app/(main)/_components/global-navigation/global-navigation.tsx
  app/src/app/(main)/_components/header/header.tsx
  app/src/app/(main)/_components/header/index.ts
  app/src/app/(main)/_components/login-form/login-form.css.ts
  app/src/app/(main)/_components/login-form/login-form.tsx
  app/src/app/(main)/_components/logo/index.ts
  app/src/app/(main)/_components/logo/logo.stories.tsx
  app/src/app/(main)/_components/logo/logo.tsx
  app/src/app/(main)/_components/page-header/index.ts
  app/src/app/(main)/_components/page-header/page-header-presenter.tsx
  app/src/app/(main)/_components/page-header/page-header.css.ts
  app/src/app/(main)/_components/page-header/page-header.stories.tsx
  app/src/app/(main)/_components/page-header/page-header.tsx
  app/src/app/(main)/login/layout.tsx
  app/src/app/(main)/new/layout.tsx
  app/src/app/(main)/privacy/layout.tsx
  app/src/app/(main)/shuffle/layout.tsx
  app/src/app/_icons/looks-to-me-black.svg
  app/src/app/_icons/looks-to-me-white.svg
Labels: feature

#281 [refactor] Rename user_providers column name
  app/migrations/0005_violet_sue_storm.sql
  app/migrations/meta/0005_snapshot.json
  app/migrations/meta/_journal.json
  app/src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
  app/src/app/_libs/db/schema/tables/user-providers.ts
Labels: refactor

#282 [feature] Add the endpoint to retrieve the avatar image
  app/src/app/(main)/_components/avatar-menu/avatar-menu.stories.tsx
  app/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  app/src/app/(main)/_components/page-header/page-header-presenter.tsx
  app/src/app/(main)/_components/page-header/page-header.stories.tsx
  app/src/app/(main)/_components/page-header/page-header.tsx
  app/src/app/(main)/_components/sync-o-auth-user/actions/upsert-user.ts
  app/src/app/(main)/_repositories/user-provider-repository.ts
  app/src/app/(main)/_repositories/user-repository.ts
  app/src/app/(main)/images/avatars/[id]/route.ts
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
Labels: feature

#285 [chore] Add a jsx lint rules
  .eslintrc.json
  app/.eslintrc.json
  app/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.tsx
  app/src/app/(main)/new/_components/post-create-form/post-create-form.tsx
  app/src/app/(main)/new/_components/variable-text-input/variable-text-input.tsx
  app/src/app/_components/infinite-scroll/infinite-scroll.tsx
Labels: chore

#286 [feature] Make the size of the posted image to be adjusted and returned
  app/migrations/0006_noisy_stature.sql
  app/migrations/meta/0006_snapshot.json
  app/migrations/meta/_journal.json
  app/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  app/src/app/(main)/_components/page-header/page-header-presenter.tsx
  app/src/app/(main)/_components/page-header/page-header.tsx
  app/src/app/(main)/_repositories/image-repository.ts
  app/src/app/(main)/_repositories/post-repository.ts
  app/src/app/(main)/_repositories/user-provider-repository.ts
  app/src/app/(main)/_repositories/user-repository.ts
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/README.md
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/index.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/gif.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/jpeg.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/png.ts
  app/src/app/(main)/images/posts/[id]/_helpers/image-size/lib/utils.ts
  app/src/app/(main)/images/posts/[id]/raw/route.ts
  app/src/app/(main)/images/posts/[id]/route.ts
  app/src/app/(main)/new/_components/input-image-with-preview/input-image-with-preview.tsx
  app/src/app/(main)/new/_components/post-create-form/actions/submitPost.ts
  app/src/app/_libs/db/schema/tables/images.ts
  workers/image-overlay/src/worker.ts
Labels: feature

#289 [bugfix] Avoid exporting variables from the API routes
  app/src/app/(main)/images/overlays/[word]/route.tsx
  app/src/app/(main)/images/posts/[id]/route.ts
Labels: bugfix

#290 [bugfix] Fix omissions in specifying options when composing images
  workers/image-overlay/src/worker.ts
Labels: bugfix

#223 [feature] Add avatar component
  app/package.json
  app/src/app/(main)/_components/avatar-menu/avatar-menu.css.ts
  app/src/app/(main)/_components/avatar-menu/avatar-menu.stories.tsx
  app/src/app/(main)/_components/avatar-menu/avatar-menu.tsx
  app/src/app/(main)/_components/page-header/page-header.css.ts
  app/src/app/_components/avatar/avatar-fallback.tsx
  app/src/app/_components/avatar/avatar-image.tsx
  app/src/app/_components/avatar/avatar.css.ts
  app/src/app/_components/avatar/avatar.stories.tsx
  app/src/app/_components/avatar/avatar.tsx
  app/src/app/_components/avatar/index.ts
  app/src/app/_theme/dark.css.ts
  app/src/app/_theme/light.css.ts
  app/src/app/_theme/theme.css.ts
  pnpm-lock.yaml
Labels: feature

#292 [feature] Add a temporary page for post details
  app/src/app/(main)/[atUsername]/_helpers/getUserName.ts
  app/src/app/(main)/[atUsername]/page.tsx
  app/src/app/(main)/[atUsername]/posts/[postId]/layout.css.ts
  app/src/app/(main)/[atUsername]/posts/[postId]/layout.tsx
  app/src/app/(main)/[atUsername]/posts/[postId]/page.tsx
  app/src/app/(main)/_repositories/user-repository.ts
Labels: feature
