Repository looks-to-me/looks-to-me, pull requests merged in 2023-07, with the labels that each got.

#14 [feature] vscode用の設定ファイルを置いた
  .vscode/settings.json
Labels: feature

#17 [chore] Enable strict-peer-dependencies
  .npmrc
Labels: chore

#28 [chore] Add a Storybook
  .eslintignore
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  next.config.js
  package.json
  patches/esbuild-register@3.4.2.patch
  pnpm-lock.yaml
  tsconfig.json
Labels: chore

#32 [chore] Fix CI that may be subject to script injection attacks
  .github/workflows/consistent-pull-request.yml
Labels: chore

#33 [chore] Make global styles apply to storybooks
  .storybook/preview.tsx
  src/app/_components/root/index.ts
  src/app/_components/root/root.css.ts
  src/app/_components/root/root.tsx
  src/app/layout.tsx
Labels: chore

#34 [feature] Add a Button component
  package.json
  pnpm-lock.yaml
  src/app/_components/button/button.css.ts
  src/app/_components/button/button.stories.tsx
  src/app/_components/button/button.tsx
  src/app/_components/button/index.ts
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#35 [refactor] Refactor the style themes
  src/app/_components/button/button.css.ts
  src/app/_components/root/root.css.ts
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: refactor

#40 [chore] Add a scaffolding tool
  .eslintignore
  .scaffdog/component.md
  .scaffdog/config.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: chore

#41 [bugfix] Fix the template for the RefForwarding component
  .scaffdog/component.md
Labels: bugfix

#64 [chore] Add a publish workflow
  .github/workflows/pr-push-check.yml
  .github/workflows/publish.yml
Labels: chore

#56 [feature] Make it possible to connect to CloudflareD1 from the server side
  package.json
  pnpm-lock.yaml
  src/app/_libs/db/index.ts
  src/app/_libs/env/index.ts
Labels: feature

#65 [feature] Make it possible to perform database migration
  .github/workflows/migration.yml
  .gitignore
  drizzle.config.ts
  migrations/0000_unique_lilith.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/_journal.json
  package.json
  pnpm-lock.yaml
  src/app/_libs/db/index.ts
  src/app/_libs/db/schema/index.ts
  src/app/_libs/db/schema/tables/users.ts
  wrangler.toml
Labels: feature

#90 [refactor] Make environment variables be called at runtime
  src/app/_helpers/memoize.ts
  src/app/_libs/db/index.ts
  src/app/_libs/env/index.ts
Labels: refactor

#95 [chore] Make lint not run at build time
  .github/workflows/pr-push-check.yml
  next.config.js
  package.json
Labels: chore

#96 [feature] Add a header component
  .scaffdog/component.md
  next.config.js
  src/app/_components/header/header.css.ts
  src/app/_components/header/header.stories.tsx
  src/app/_components/header/header.tsx
  src/app/_components/header/index.ts
  src/app/page.tsx
Labels: feature

#100 [feature] Make it possible to import SVG files directly using SVGR
  .storybook/main.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  svgr.d.ts
  tsconfig.json
Labels: feature

#101 [feature] Add a external link to the header
  src/app/_components/header/header.css.ts
  src/app/_components/header/header.tsx
  src/app/_components/prefers-color-scheme/index.ts
  src/app/_components/prefers-color-scheme/prefers-color-scheme.css.ts
  src/app/_components/prefers-color-scheme/prefers-color-scheme.stories.tsx
  src/app/_components/prefers-color-scheme/prefers-color-scheme.tsx
  src/app/_helpers/mergeProps.ts
  src/app/_icons/github-black.svg
  src/app/_icons/github-white.svg
  src/app/_icons/storybook-black.svg
  src/app/_icons/storybook-white.svg
Labels: feature

#111 [feature] Add a sheet component
  package.json
  pnpm-lock.yaml
  src/app/_components/sheet/index.ts
  src/app/_components/sheet/sheet-close.tsx
  src/app/_components/sheet/sheet-content.tsx
  src/app/_components/sheet/sheet-description.tsx
  src/app/_components/sheet/sheet-title.tsx
  src/app/_components/sheet/sheet-trigger.tsx
  src/app/_components/sheet/sheet.css.ts
  src/app/_components/sheet/sheet.stories.tsx
  src/app/_components/sheet/sheet.tsx
  src/app/_icons/close.svg
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#112 [refactor] Remove redundant type specification of forwardRef
  .scaffdog/component.md
  src/app/_components/button/button.tsx
  src/app/_components/header/header.tsx
Labels: refactor

#119 [feature] Add a logo component
  src/app/_components/header/header.tsx
  src/app/_components/logo/index.ts
  src/app/_components/logo/logo.css.ts
  src/app/_components/logo/logo.stories.tsx
  src/app/_components/logo/logo.tsx
Labels: feature

#120 [feature] Add a separator component
  package.json
  pnpm-lock.yaml
  src/app/_components/separator/index.ts
  src/app/_components/separator/separator.css.ts
  src/app/_components/separator/separator.stories.tsx
  src/app/_components/separator/separator.tsx
Labels: feature

#123 [feature] Add a visually hidden component
  package.json
  pnpm-lock.yaml
  src/app/_components/visually-hidden/index.ts
  src/app/_components/visually-hidden/visually-hidden.stories.tsx
  src/app/_components/visually-hidden/visually-hidden.tsx
Labels: feature

#124 [feature] Add a accessible icon component
  package.json
  pnpm-lock.yaml
  src/app/_components/accessible-icon/accessible-icon.stories.tsx
  src/app/_components/accessible-icon/accessible-icon.tsx
  src/app/_components/accessible-icon/index.ts
  src/app/_components/sheet/sheet-content.tsx
Labels: feature

#125 [feature] Add styles for anchor element
  src/app/_components/accessible-icon/accessible-icon.stories.tsx
  src/app/_components/button/button.stories.tsx
  src/app/_components/root/root.css.ts
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
  src/app/_theme/theme.css.ts
Labels: feature

#127 [chore] Specify the format of the type import
  .eslintrc.json
Labels: chore

#129 [chore] Prevent blank lines between adjacent elements
  .eslintrc.json
Labels: chore

#130 [feature] Add a sheet section component
  src/app/_components/sheet/index.ts
  src/app/_components/sheet/sheet-content.tsx
  src/app/_components/sheet/sheet-section.tsx
  src/app/_components/sheet/sheet.css.ts
  src/app/_components/sheet/sheet.stories.tsx
Labels: feature

#131 [feature] Add a global navigation component
  package.json
  pnpm-lock.yaml
  src/app/_components/accessible-icon/accessible-icon.tsx
  src/app/_components/button/button.css.ts
  src/app/_components/global-navigation/global-navigation.css.ts
  src/app/_components/global-navigation/global-navigation.stories.tsx
  src/app/_components/global-navigation/global-navigation.tsx
  src/app/_components/global-navigation/index.ts
  src/app/_components/header/header.tsx
  src/app/_components/sheet/sheet.css.ts
  src/app/_components/visually-hidden/visually-hidden.tsx
  src/app/_icons/menu.svg
  src/app/_icons/report.svg
  src/app/_theme/dark.css.ts
  src/app/_theme/light.css.ts
Labels: feature

#99 [feature] supabaseで認証
  .env
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
  src/app/_components/root/root.tsx
  src/app/_components/sign-in-button/index.ts
  src/app/_components/sign-in-button/sign-in-button.stories.tsx
  src/app/_components/sign-in-button/sign-in-button.tsx
  src/app/_components/sign-out-button/index.ts
  src/app/_components/sign-out-button/sign-out-button.stories.tsx
  src/app/_components/sign-out-button/sign-out-button.tsx
  src/app/_libs/supabase/client-instance.ts
  src/app/_libs/supabase/client-session-provider.tsx
  src/app/_libs/supabase/get-server-session.ts
  src/app/_libs/supabase/server-instance.ts
  src/app/auth/callback/route.ts
  src/app/page.tsx
  src/middleware.ts
Labels: feature

#132 [chore] Make the file next-env.d.ts the target of the commit
  .gitignore
  next-env.d.ts
Labels: chore

#133 [refactor] Make directories separate for servers and clients
  src/app/_components/root/root.tsx
  src/app/_components/sign-in-button/sign-in-button.tsx
  src/app/_components/sign-out-button/sign-out-button.tsx
  src/app/_libs/auth/client/instance.ts
  src/app/_libs/auth/client/session-provider.tsx
  src/app/_libs/auth/server/get-session.ts
  src/app/_libs/auth/server/instance.ts
  src/app/_libs/supabase/client-session-provider.tsx
  src/app/_libs/supabase/get-server-session.ts
  src/app/auth/callback/route.ts
  src/app/page.tsx
Labels: refactor

#134 [feature] Add a function to retrieve the authenticated user
  pnpm-lock.yaml
  src/app/_libs/auth/server/get-session.ts
  src/app/_libs/auth/server/get-user.ts
  src/app/_libs/auth/type/user.ts
  src/app/page.tsx
Labels: feature

#135 [refactor] Rename from Signin/Signout to Login/Logout
  src/app/_components/button/button.css.ts
  src/app/_components/global-navigation/global-navigation.css.ts
  src/app/_components/global-navigation/global-navigation.tsx
  src/app/_components/login-button/index.ts
  src/app/_components/login-button/login-button.css.ts
  src/app/_components/login-button/login-button.stories.tsx
  src/app/_components/login-button/login-button.tsx
  src/app/_components/logout-button/index.ts
  src/app/_components/logout-button/logout-button.stories.tsx
  src/app/_components/logout-button/logout-button.tsx
  src/app/_components/sign-in-button/index.ts
  src/app/_components/sign-in-button/sign-in-button.tsx
  src/app/_components/sign-out-button/index.ts
  src/app/_components/sign-out-button/sign-out-button.tsx
  src/app/page.tsx
Labels: refactor

#136 [refactor] Change the type name of the authenticated user
  src/app/_libs/auth/server/get-auth-user.ts
  src/app/_libs/auth/type/auth-user.ts
  src/app/page.tsx
Labels: refactor

#137 [refactor] Make the header component include a login/logout button
  src/app/_components/header/header.css.ts
  src/app/_components/header/header.stories.tsx
  src/app/_components/header/header.tsx
  src/app/page.tsx
Labels: refactor

#138 [chore] Make the environment be specified according to the branch at …
  .github/workflows/publish.yml
Labels: chore
